version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    allow:
      - dependency-name: "js-yaml"
      - dependency-name: "@babel/core"
    groups:
      pilot-security:
        applies-to: security-updates
        patterns:
          - "*"
