-- GENERATED by scripts/security/gen-security-catalog.mjs — DO NOT EDIT BY HAND.
-- Regenerate after adding a migration; CI (sec-c-tenant-db-ci.yml) fails if stale.
--
-- sec(C) — READ-ONLY production security-catalog assertions.
--
-- Prints ONE row per assertion: id, PASS/FAIL, a count, and — only on FAIL —
-- the offending catalog identifiers (table / policy / role / constraint names).
-- It never selects a row of application data. The repository is public, so this
-- output is designed to be public too.
--
-- Expected state = the repository's migrations (150 directories):
--   119 tables with RLS ENABLED + FORCED, 20 tables deliberately without RLS,
--   150 statically-declared policies, 9 composite tenant FKs, 2 definer lookups.
-- Role groups checked: app_runtime, app_auth, app_admin, app_ctlplane and every
-- LOGIN member of them.

SET statement_timeout = '60s';
SET default_transaction_read_only = on;
BEGIN TRANSACTION READ ONLY;

WITH
expected_rls(t) AS (SELECT unnest(ARRAY[
    'Appointment',
    'BillingAuditEvent',
    'BillingAuthorityConnection',
    'BillingAuthoritySubmission',
    'BillingDocument',
    'BillingDocumentLine',
    'BillingDocumentNumberSequence',
    'BillingPaymentAllocation',
    'BillingReceiptPayment',
    'BotGoalSelection',
    'BusinessBankAccount',
    'BusinessBot',
    'BusinessBotKnowledge',
    'BusinessBotLearningSuggestion',
    'BusinessBotMemoryPolicy',
    'BusinessBotProfile',
    'BusinessBotRecommendation',
    'BusinessBotSettings',
    'BusinessBotSetupDraft',
    'BusinessFeatureAccess',
    'BusinessInsight',
    'BusinessObligation',
    'BusinessObligationOrientation',
    'BusinessPaymentConnection',
    'BusinessProfile',
    'BusinessService',
    'Cheque',
    'CollaborationDeal',
    'CollectionAction',
    'Commitment',
    'ContentEvent',
    'ContentRender',
    'ContentRun',
    'ContentVariant',
    'Conversation',
    'CrmAttachment',
    'CrmNote',
    'Customer',
    'Deal',
    'DerivedClaimCandidate',
    'DerivedClaimEvidenceLink',
    'DerivedClaimProjection',
    'Document',
    'EmailAttachmentImport',
    'EmailConnection',
    'EntityLinkProposal',
    'ExternalTransaction',
    'ExternalTransactionMatchRejection',
    'ExtractedData',
    'ExtractionEvidence',
    'ExtractionSnapshot',
    'FinancialDocument',
    'FinancialEvent',
    'FinancialRecord',
    'HistoricalFiscalDocument',
    'ImportRun',
    'ImportRunRow',
    'InboundEmailAddress',
    'InboundEmailAttachmentImport',
    'InboundEmailAuthorizedSender',
    'InboundEmailMessage',
    'InboundEmailSenderChallenge',
    'Installment',
    'InventoryAlert',
    'InventoryCategory',
    'InventoryDraft',
    'InventoryExternalSale',
    'InventoryItem',
    'InventoryMovement',
    'InventoryPendingMatch',
    'KnowledgeMeasure',
    'KnowledgeMeasureEvidenceLink',
    'Lead',
    'LearningEvent',
    'LearningSignal',
    'Message',
    'MessageAnalysis',
    'Notification',
    'NotificationDelivery',
    'OAuthToken',
    'OutboundExecution',
    'Party',
    'PartyResolutionClaim',
    'PayablesAuditEvent',
    'PayablesMatchRejection',
    'Payee',
    'Payment',
    'PaymentAccountingSettlement',
    'PaymentAllocation',
    'PaymentAuditEvent',
    'PaymentDestination',
    'PaymentEvidence',
    'PaymentPreparation',
    'PaymentRequest',
    'PaymentTransaction',
    'POSProductMapping',
    'PricingCalculation',
    'PricingProfile',
    'PricingRecommendation',
    'PurchaseOrder',
    'PurchaseOrderLine',
    'ReceivingLine',
    'ReceivingSession',
    'Recommendation',
    'RecommendationOutcome',
    'ReplySuggestion',
    'ReviewEvent',
    'RiaCanonicalReferent',
    'RiaPolicyLineage',
    'ServiceCostProfile',
    'SliceDecision',
    'Supplier',
    'SupplierPurchaseDraft',
    'SupplierPurchaseDraftLine',
    'Task',
    'TemporalKnowledge',
    'Usage',
    'VendorLearning',
    'WhatsAppAttachmentImport'
  ]::text[])),
expected_non_rls(t) AS (SELECT unnest(ARRAY[
    'AuthSession',
    'AuthSessionSecret',
    'BillingAuthorityApp',
    'Business',
    'ContentFeedback',
    'Coupon',
    'DerivationPolicy',
    'DerivationPolicyVersion',
    'Offer',
    'PaymentProviderRouting',
    'PaymentWebhookEvent',
    'PlatformAdminMfa',
    'PlatformAuditEvent',
    'PlatformFeatureDefinition',
    'PlatformFeaturePolicy',
    'POSApiKey',
    'ProductUsageEvent',
    'RedemptionEvent',
    'User',
    'WhatsAppConnection'
  ]::text[])),
expected_policies(tp) AS (SELECT unnest(ARRAY[
    'Appointment.p7pilot_tenant_insert',
    'Appointment.p7pilot_tenant_read',
    'Appointment.p7pilot_tenant_update',
    'BillingAuditEvent.p7w4eb2_tenant',
    'BillingAuthorityConnection.p7w4eb2_tenant',
    'BillingAuthoritySubmission.p7w4eb2_tenant',
    'BillingDocument.p7adm_read',
    'BillingDocument.p7pilot_tenant_insert',
    'BillingDocument.p7pilot_tenant_read',
    'BillingDocument.p7pilot_tenant_update',
    'BillingDocumentLine.p7w4eb2_tenant',
    'BillingDocumentNumberSequence.p7w4eb2_tenant',
    'BillingPaymentAllocation.p7w4eb2_tenant',
    'BillingReceiptPayment.p7w4eb2_tenant',
    'BotGoalSelection.p7w2_tenant',
    'BusinessBankAccount.payables_p3_tenant',
    'BusinessBot.p7w4eb2_tenant',
    'BusinessBotKnowledge.p7w2_tenant',
    'BusinessBotLearningSuggestion.p7w2_tenant',
    'BusinessBotMemoryPolicy.p7w2_tenant',
    'BusinessBotProfile.p7w2_tenant',
    'BusinessBotRecommendation.p7w2_tenant',
    'BusinessBotSettings.p7w4b_tenant',
    'BusinessBotSetupDraft.p7w2_tenant',
    'BusinessFeatureAccess.p7pw2_ctl_insert',
    'BusinessFeatureAccess.p7pw2_ctl_update',
    'BusinessFeatureAccess.p7pw2_tenant_read',
    'BusinessInsight.p7w2_tenant',
    'BusinessObligation.p7w1_tenant',
    'BusinessObligationOrientation.p7w1_tenant',
    'BusinessPaymentConnection.p7w4ea_tenant',
    'BusinessProfile.p7w1_tenant',
    'BusinessService.p7w1_tenant',
    'Cheque.payables_p3_tenant',
    'CollaborationDeal.p7w1_tenant',
    'CollectionAction.p7w2_tenant',
    'Commitment.payables_p1a_tenant',
    'ContentEvent.p7w2_tenant',
    'ContentRender.p7w2_tenant',
    'ContentRun.p7adm_read',
    'ContentRun.p7w2_tenant',
    'ContentVariant.p7w2_tenant',
    'Conversation.p7adm_read',
    'Conversation.p7pilot_tenant_insert',
    'Conversation.p7pilot_tenant_read',
    'Conversation.p7pilot_tenant_update',
    'CrmAttachment.p7w1_tenant',
    'CrmNote.p7w1_tenant',
    'Customer.p7pilot_tenant_insert',
    'Customer.p7pilot_tenant_read',
    'Customer.p7pilot_tenant_update',
    'Deal.p7w1_tenant',
    'DerivedClaimCandidate.p7w2_tenant',
    'DerivedClaimEvidenceLink.p7w2_tenant',
    'DerivedClaimProjection.p7w2_tenant',
    'Document.p7adm_read',
    'Document.p7w4d_tenant',
    'EmailAttachmentImport.p7w4c_tenant',
    'EmailConnection.p7adm_read',
    'EmailConnection.p7w4c_tenant',
    'EntityLinkProposal.p7w2_tenant',
    'ExternalTransaction.payables_p46_tenant',
    'ExternalTransactionMatchRejection.payables_p46_tenant',
    'ExtractedData.p7w4d_tenant',
    'ExtractionEvidence.p7adm_read',
    'ExtractionEvidence.p7w4d_tenant',
    'ExtractionSnapshot.p7adm_read',
    'ExtractionSnapshot.p7w4d_tenant',
    'FinancialDocument.p7w2_tenant',
    'FinancialEvent.p7w4ea_tenant',
    'FinancialRecord.p7adm_read',
    'FinancialRecord.p7w4d_tenant',
    'HistoricalFiscalDocument.i8a_hist_tenant_insert',
    'HistoricalFiscalDocument.i8a_hist_tenant_read',
    'ImportRun.p7imp_tenant_delete',
    'ImportRun.p7imp_tenant_insert',
    'ImportRun.p7imp_tenant_read',
    'ImportRun.p7imp_tenant_update',
    'ImportRunRow.p7imp_row_tenant_delete',
    'ImportRunRow.p7imp_row_tenant_insert',
    'ImportRunRow.p7imp_row_tenant_read',
    'InboundEmailAddress.inbound_addr_tenant',
    'InboundEmailAttachmentImport.inbound_att_tenant',
    'InboundEmailAuthorizedSender.inbound_sender_tenant',
    'InboundEmailMessage.inbound_msg_tenant',
    'InboundEmailSenderChallenge.inbound_challenge_tenant',
    'Installment.payables_p1a_tenant',
    'InventoryAlert.p7w3_tenant',
    'InventoryCategory.p7w3_tenant',
    'InventoryDraft.p7w3_tenant',
    'InventoryExternalSale.p7w3_tenant',
    'InventoryItem.p7w3_tenant',
    'InventoryMovement.p7w3_tenant',
    'InventoryPendingMatch.p7w3_tenant',
    'KnowledgeMeasure.p7w2_tenant',
    'KnowledgeMeasureEvidenceLink.p7w2_tenant',
    'Lead.p7w1_tenant',
    'LearningEvent.p7w2_tenant',
    'LearningSignal.p7w2_tenant',
    'Message.p7w4b_tenant',
    'MessageAnalysis.p7w4b_tenant',
    'Notification.notif_tenant',
    'NotificationDelivery.notif_delivery_tenant',
    'OAuthToken.p7w4c_tenant',
    'OutboundExecution.payables_p46_tenant',
    'Party.p7w2_tenant',
    'PartyResolutionClaim.p7w2_tenant',
    'PayablesAuditEvent.payables_p1a_tenant',
    'PayablesMatchRejection.payables_p2_tenant',
    'Payee.payables_p1a_tenant',
    'Payment.payables_p1a_tenant',
    'PaymentAccountingSettlement.c3_settlement_tenant_insert',
    'PaymentAccountingSettlement.c3_settlement_tenant_read',
    'PaymentAccountingSettlement.c3_settlement_tenant_update',
    'PaymentAllocation.payables_p1a_tenant',
    'PaymentAuditEvent.p7w4ea_tenant',
    'PaymentDestination.payables_p46_tenant',
    'PaymentEvidence.payables_p1a_tenant',
    'PaymentPreparation.payables_p46_tenant',
    'PaymentRequest.p7pilot_tenant_insert',
    'PaymentRequest.p7pilot_tenant_read',
    'PaymentRequest.p7pilot_tenant_update',
    'PaymentTransaction.p7w4ea_tenant',
    'POSProductMapping.p7w3_tenant',
    'PricingCalculation.p7w1_tenant',
    'PricingProfile.p7w1_tenant',
    'PricingRecommendation.p7w1_tenant',
    'PurchaseOrder.p7w3_tenant',
    'PurchaseOrderLine.p7w3_tenant',
    'ReceivingLine.p7w3_tenant',
    'ReceivingSession.p7w3_tenant',
    'Recommendation.p7w2_tenant',
    'RecommendationOutcome.p7w2_tenant',
    'ReplySuggestion.p7w4b_tenant',
    'ReviewEvent.p7adm_read',
    'ReviewEvent.p7w4d_tenant',
    'RiaCanonicalReferent.p7w2_tenant',
    'RiaPolicyLineage.p7w2_tenant',
    'ServiceCostProfile.p7w1_tenant',
    'SliceDecision.p7adm_read',
    'SliceDecision.p7w4d_tenant',
    'Supplier.p7w3_tenant',
    'SupplierPurchaseDraft.p7w3_tenant',
    'SupplierPurchaseDraftLine.p7w3_tenant',
    'Task.p7w1_tenant',
    'TemporalKnowledge.p7w2_tenant',
    'Usage.p7w2_tenant',
    'VendorLearning.p7w4d_tenant',
    'WhatsAppAttachmentImport.p7adm_read',
    'WhatsAppAttachmentImport.p7w4b_tenant'
  ]::text[])),
expected_migrations(m) AS (SELECT unnest(ARRAY[
    '20260210120000_billing_invoice_profile_fields',
    '20260329225659_init',
    '20260330142739_core_data_layer_v1',
    '20260404180953_add_message_analysis',
    '20260404192959_add_strategy_variant_type',
    '20260408175347_add_user_foundation',
    '20260409200322_add_pricing_engine_models',
    '20260409201448_add_pricing_engine_models',
    '20260411204133_move_business_fields_to_profile',
    '20260411231702_business_profile_v1',
    '20260413141745_add_deals',
    '20260413160913_collaboration_v2_matching_fields',
    '20260414101056_add_revenue_activation_v1',
    '20260415141145_add_redeem_engine_and_fix_relations',
    '20260416123915_add_content_feedback',
    '20260416181707_add_document_engine_v1',
    '20260416190435_upgrade_vendor_learning_v2',
    '20260421141909_add_usage_model',
    '20260423112200_add_inventory_intelligence_v1',
    '20260423121208_add_inventory_draft_merge_link',
    '20260423230912_add_inventory_alert_types',
    '20260424101150_add_external_sales',
    '20260424111131_add_inventory_pending_match_relations',
    '20260424135210_add_extraction_fields',
    '20260424141045_add_category_suggestion',
    '20260505101018_add_email_ingestion_models',
    '20260505124400_reconcile_schema_history',
    '20260506131728_add_offer_image_url',
    '20260506151600_add_coupon_public_id',
    '20260507141435_add_billing_module',
    '20260508123333_add_inventory_item_supplier_name',
    '20260510120630_add_financial_event_phase_a',
    '20260510140000_billing_business_kind',
    '20260510180000_billing_pdf_template_style',
    '20260511123000_add_billing_quote_mvp',
    '20260512120000_add_pos_api_key',
    '20260513120000_add_business_bot_settings',
    '20260513193000_add_show_draft_suggestions_in_inbox',
    '20260514100000_add_product_link_fields',
    '20260514120000_add_content_persistence_models',
    '20260517204000_add_billing_immutable_issued_fields',
    '20260517223000_add_billing_credit_note_foundation',
    '20260518001000_add_billing_audit_events',
    '20260526120000_whatsapp_attachment_import',
    '20260527120000_platform_admin_foundation',
    '20260527140000_product_usage_analytics_foundation',
    '20260528120000_platform_feature_access_foundation',
    '20260528130000_whatsapp_connection_and_customer_phone_unique',
    '20260531120000_conversation_pending_state',
    '20260531190000_add_purchase_orders_phase1',
    '20260531200000_add_receiving_sessions_phase2',
    '20260531210000_add_purchase_order_remaining_decisions_phase3',
    '20260601100000_add_cost_layer_basic_phase4',
    '20260601120000_appointment_object',
    '20260601200000_add_supplier_foundation_phase5a',
    '20260603120000_add_supplier_purchase_draft_line_unit_cost',
    '20260608120000_add_customer_billing_tax_identity',
    '20260609120000_add_business_archive_fields',
    '20260610120000_h1b1_billing_fk_restrict',
    '20260610130000_authority_foundation_phase_c',
    '20260610140000_party_resolution_foundation_t1',
    '20260610150000_party_anchor_claim_t2_readiness',
    '20260611120000_billing_authority_allocation_projection',
    '20260615120000_receipt_payment_doctype_enum',
    '20260615120100_receipt_payment_tables',
    '20260618120000_add_correction_ledger',
    '20260624140000_add_payments_foundation',
    '20260624150000_add_cardcom_payment_provider',
    '20260624170000_add_business_bot_profile',
    '20260624180000_add_bot_goal_selection',
    '20260624190000_add_bot_setup_and_knowledge',
    '20260625120000_add_activation_and_recommendations',
    '20260625130000_add_memory_policy_and_learning',
    '20260625140000_add_general_decision_ledger',
    '20260625150000_add_ledger_layer_stage',
    '20260629120000_add_documents_search_indexes',
    '20260629130000_add_payment_audit_event',
    '20260630120000_add_business_obligation_domain',
    '20260705120000_add_paypal_provider',
    '20260705140000_add_learning_capture_gaps',
    '20260707120000_add_business_location_hours',
    '20260715120000_add_crm_notes',
    '20260716120000_add_authority_submission_held',
    '20260716120000_add_crm_attachments',
    '20260721131204_add_supplier_relation_to_purchase_orders',
    '20260724120000_add_customer_lifecycle',
    '20260814120000_add_ria_canonical_referent',
    '20260815120000_add_ria_policy_lineage',
    '20260817120000_add_derivation_policy_substrate',
    '20260817130000_add_billing_signature_data_url',
    '20260818120000_add_derived_claim_substrate',
    '20260818130000_bootstrap_vendor_category_policy_v1',
    '20260818140000_add_signed_pdf_artifact',
    '20260820120000_add_billing_payment_terms_days',
    '20260823120000_add_business_deletion_lifecycle',
    '20260824210000_d2_p7_wave1_tenant_rls',
    '20260825090000_d2_p7_w2gate_admin_read',
    '20260825120000_d2_p7_wave1_businessprofile_rls',
    '20260825150000_d2_p7_wave2_tenant_rls',
    '20260825200000_d2_p7_wave3_tenant_rls',
    '20260826090000_d2_p7_w4a_message_provider_unique',
    '20260826120000_documents_dedup_identity',
    '20260826150000_d2_p7_w4b_whatsapp_tenant_rls',
    '20260826200000_d2_p7_w4c_gmail_tenant_rls',
    '20260827090000_d2_p7_w4d_documents_tenant_rls',
    '20260830120000_d2_p7_w4ea_payments_tenant_rls',
    '20260831090000_leads_w1_core',
    '20260831120000_d2_p7_w4eb2_billing_tenant_rls',
    '20260831130000_supplier_domain_wiring',
    '20260831170000_w25_message_hardening',
    '20260901090000_d2_pw2_business_feature_access_rls',
    '20260901120000_casa_wave_b_platform_admin_mfa',
    '20260902090000_d2_ad2a3_conversation_tenant_coherence',
    '20260902100000_auth_token_version',
    '20260902120000_d2_cutover2b_pilot_tenant_rls',
    '20260903090000_import_run_execution_ledger',
    '20260903200000_notification_persistence',
    '20260907120000_i8a_historical_fiscal_documents',
    '20260908120000_persistent_auth_sessions',
    '20260908180000_d2_user_business_privilege_narrowing',
    '20260908200000_auth_session_privilege_contract',
    '20260909020000_add_payplus_provider',
    '20260913120000_authsession_user_agent',
    '20260914120000_inbound_email_foundation',
    '20260915090000_f01_import_retry_identity',
    '20260915120000_businessprofile_runtime_grants',
    '20260915130000_add_sumit_provider',
    '20260915130100_payment_routing_callback_secret',
    '20260916090000_inbound_email_authorized_senders',
    '20260917090000_payables_phase_1a_foundation',
    '20260917090100_payables_phase_1a_tenant_rls',
    '20260917090200_payables_phase_1a_obligation_backfill',
    '20260917100000_inbound_address_retirement_and_sender_reregistration',
    '20260918090000_payables_phase_2_document_evidence',
    '20260918120000_payables_phase_3_cheques_and_bank_accounts',
    '20260918140000_inbound_email_challenge_purpose_and_lifecycle',
    '20260922090000_c3_payment_accounting_settlement',
    '20260922130000_payables_p4_p6_outbound_foundation',
    '20260923090000_m0_derived_claim_evidence_link_tenant_fk',
    '20260923100000_m2_knowledge_measure',
    '20260923110000_m3_business_insight',
    '20260924090000_m5_identity_enum_expansion',
    '20260924090100_m4_m5_knowledge_expansion',
    '20260924180000_m5_collection_action_append_only',
    '20260925090000_m55_sensor_fabric',
    '20260926090000_m6_temporal_knowledge',
    '20260926110000_sec_c_tenant_composite_fk',
    '20260926110100_sec_c_bootstrap_lookup_functions',
    '20260926110200_sec_c_admin_read_whatsapp_attachment_import',
    '20260926110300_sec_c_explicit_identity_grants'
  ]::text[])),
expected_fks(c) AS (SELECT unnest(ARRAY[
    'Appointment_customerId_tenant_fkey',
    'Appointment_leadId_tenant_fkey',
    'Appointment_sourceConversationId_tenant_fkey',
    'Appointment_sourceMessageId_tenant_fkey',
    'Conversation_customerId_tenant_fkey',
    'Conversation_leadId_tenant_fkey',
    'Lead_customerId_tenant_fkey',
    'Message_customerId_tenant_fkey',
    'Message_generatedFromSuggestionId_tenant_fkey'
  ]::text[])),
expected_fns(f) AS (SELECT unnest(ARRAY[
    'sec_c_pos_api_key_lookup',
    'sec_c_whatsapp_business_by_phone_number_id'
  ]::text[])),
tbl AS (
  SELECT c.oid, c.relname AS t, c.relrowsecurity AS rls, c.relforcerowsecurity AS force,
         pg_get_userbyid(c.relowner) AS owner
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND c.relname <> '_prisma_migrations'
),
groups AS (
  SELECT oid, rolname FROM pg_roles WHERE rolname IN ('app_runtime', 'app_auth', 'app_admin', 'app_ctlplane')
),
app_roles AS (
  SELECT r.oid, r.rolname, r.rolsuper, r.rolbypassrls, r.rolcreaterole, r.rolcreatedb, r.rolreplication, r.rolcanlogin
    FROM pg_roles r
   WHERE r.oid IN (SELECT oid FROM groups)
      OR r.oid IN (SELECT m.member FROM pg_auth_members m WHERE m.roleid IN (SELECT oid FROM groups))
),
runtime_roles AS (
  SELECT oid, rolname FROM pg_roles WHERE rolname = 'app_runtime'
  UNION SELECT r.oid, r.rolname FROM pg_roles r JOIN pg_auth_members m ON m.member = r.oid
   WHERE m.roleid = (SELECT oid FROM pg_roles WHERE rolname = 'app_runtime')
),
results AS (
  -- A1: every app role and LOGIN member is NOSUPERUSER, NOBYPASSRLS, NOCREATEROLE, NOCREATEDB, NOREPLICATION.
  SELECT 'A1_app_roles_least_privilege_attributes' AS id,
         count(*) FILTER (WHERE rolsuper OR rolbypassrls OR rolcreaterole OR rolcreatedb OR rolreplication) AS bad,
         count(*) AS total,
         string_agg(rolname, ',' ORDER BY rolname) FILTER (WHERE rolsuper OR rolbypassrls OR rolcreaterole OR rolcreatedb OR rolreplication) AS detail
    FROM app_roles
  UNION ALL
  -- A1b: the four groups exist and at least one runtime LOGIN member exists.
  SELECT 'A1b_role_groups_present',
         (4 - (SELECT count(*) FROM groups)) + CASE WHEN EXISTS (SELECT 1 FROM app_roles a JOIN runtime_roles r ON r.oid = a.oid WHERE a.rolcanlogin) THEN 0 ELSE 1 END,
         (SELECT count(*) FROM groups),
         NULLIF(concat_ws(',',
           CASE WHEN NOT EXISTS (SELECT 1 FROM groups WHERE rolname='app_runtime') THEN 'missing:app_runtime' END,
           CASE WHEN NOT EXISTS (SELECT 1 FROM groups WHERE rolname='app_auth') THEN 'missing:app_auth' END,
           CASE WHEN NOT EXISTS (SELECT 1 FROM groups WHERE rolname='app_admin') THEN 'missing:app_admin' END,
           CASE WHEN NOT EXISTS (SELECT 1 FROM groups WHERE rolname='app_ctlplane') THEN 'missing:app_ctlplane' END,
           CASE WHEN NOT EXISTS (SELECT 1 FROM app_roles a JOIN runtime_roles r ON r.oid = a.oid WHERE a.rolcanlogin) THEN 'no_runtime_login' END), '')
  UNION ALL
  -- A1c: no app role owns a public table (non-owner; FORCE RLS would otherwise be the owner's to disable).
  SELECT 'A1c_app_roles_own_no_tables',
         count(*), (SELECT count(*) FROM tbl),
         string_agg(t.t || '@' || t.owner, ',' ORDER BY t.t)
    FROM tbl t WHERE t.owner IN (SELECT rolname FROM app_roles)
  UNION ALL
  -- A2: every expected table has RLS ENABLED and FORCED.
  SELECT 'A2_expected_tables_rls_forced',
         count(*) FILTER (WHERE tb.t IS NULL OR NOT tb.rls OR NOT tb.force),
         count(*),
         string_agg(e.t || CASE WHEN tb.t IS NULL THEN ':missing' WHEN NOT tb.rls THEN ':rls_off' ELSE ':no_force' END, ',' ORDER BY e.t)
           FILTER (WHERE tb.t IS NULL OR NOT tb.rls OR NOT tb.force)
    FROM expected_rls e LEFT JOIN tbl tb ON tb.t = e.t
  UNION ALL
  -- A3: no public table is without RLS unless the repository says so.
  SELECT 'A3_no_unexpected_non_rls_tables',
         count(*), (SELECT count(*) FROM tbl WHERE NOT rls),
         string_agg(tb.t, ',' ORDER BY tb.t)
    FROM tbl tb WHERE (NOT tb.rls OR NOT tb.force) AND tb.t NOT IN (SELECT t FROM expected_non_rls)
                      AND tb.t NOT IN (SELECT t FROM expected_rls)
  UNION ALL
  -- A4: every statically-declared policy exists.
  SELECT 'A4_expected_policies_present',
         count(*) FILTER (WHERE p.policyname IS NULL), count(*),
         string_agg(e.tp, ',' ORDER BY e.tp) FILTER (WHERE p.policyname IS NULL)
    FROM expected_policies e
    LEFT JOIN pg_policies p ON p.schemaname = 'public' AND p.tablename || '.' || p.policyname = e.tp
  UNION ALL
  -- A4b: USING (true) / unconditional policies apply only to app_admin (read) or a
  -- definer owner (sec_c_definer_lookup) — never to PUBLIC or a runtime role.
  SELECT 'A4b_unconditional_policies_scoped',
         count(*), (SELECT count(*) FROM pg_policies WHERE schemaname = 'public'),
         string_agg(p.tablename || '.' || p.policyname, ',' ORDER BY p.tablename)
    FROM pg_policies p
   WHERE p.schemaname = 'public'
     AND (p.qual = 'true' OR (p.qual IS NULL AND p.with_check IS NULL))
     AND NOT (p.roles = ARRAY['app_admin']::name[] AND p.cmd = 'SELECT')
     AND p.policyname <> 'sec_c_definer_lookup'
  UNION ALL
  -- A5: the runtime (group + members) holds no TRUNCATE/REFERENCES/TRIGGER anywhere,
  -- no read of User.password, and no INSERT on User/Business.
  SELECT 'A5_runtime_privilege_ceiling',
         count(*), (SELECT count(*) FROM runtime_roles),
         string_agg(DISTINCT x.what, ',' ORDER BY x.what)
    FROM (
      SELECT r.rolname || ':' || tb.t || ':' || p.priv AS what
        FROM runtime_roles r CROSS JOIN tbl tb CROSS JOIN unnest(ARRAY['TRUNCATE','REFERENCES','TRIGGER']) p(priv)
       WHERE has_table_privilege(r.oid, tb.oid, p.priv)
      UNION ALL
      SELECT r.rolname || ':User.password:SELECT' FROM runtime_roles r
       WHERE has_column_privilege(r.oid, '"User"', 'password', 'SELECT')
      UNION ALL
      SELECT r.rolname || ':' || x.t || ':INSERT' FROM runtime_roles r CROSS JOIN (VALUES ('User'), ('Business')) x(t)
       WHERE has_table_privilege(r.oid, format('%I', x.t), 'INSERT')
    ) x
  UNION ALL
  -- A5b: app_admin cannot read the password hash.
  SELECT 'A5b_admin_cannot_read_password',
         CASE WHEN EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin')
                   AND has_column_privilege('app_admin', '"User"', 'password', 'SELECT') THEN 1 ELSE 0 END,
         1, NULL
  UNION ALL
  -- A5c: the auth plane can perform signup — every column Prisma emits on the two
  -- inserts is granted (a missing one is a 42501 on the first signup).
  SELECT 'A5c_auth_signup_insert_columns',
         count(*) FILTER (WHERE NOT ok), count(*),
         string_agg(c, ',' ORDER BY c) FILTER (WHERE NOT ok)
    FROM (
      SELECT t || '.' || col AS c,
             EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_auth')
               AND has_column_privilege('app_auth', format('%I', t), col, 'INSERT') AS ok
        FROM (VALUES ('User','email'),('User','password'),('User','name'),('User','businessId'),
                     ('User','createdAt'),('User','updatedAt'),
                     ('Business','name'),('Business','createdAt'),('Business','updatedAt')) v(t, col)
    ) x
  UNION ALL
  -- A5d: the tenant runtime holds NO privilege on platform-admin MFA state
  -- (authentication material; auth plane only). FAILs until T-04 ships and the owner
  -- revokes the runtime's legacy grant.
  SELECT 'A5d_runtime_no_platform_admin_mfa',
         count(*), (SELECT count(*) FROM runtime_roles),
         string_agg(r.rolname || ':' || p.priv, ',' ORDER BY r.rolname)
    FROM runtime_roles r CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE']) p(priv)
   WHERE to_regclass('public."PlatformAdminMfa"') IS NOT NULL
     AND has_table_privilege(r.oid, 'public."PlatformAdminMfa"', p.priv)
  UNION ALL
  -- A6: default-deny — no default ACL hands the runtime anything on new tables/sequences.
  SELECT 'A6_no_runtime_default_privileges',
         count(*), (SELECT count(*) FROM pg_default_acl),
         string_agg(DISTINCT pg_get_userbyid(d.defaclrole) || '->' || pg_get_userbyid(g.grantee) || ':' || d.defaclobjtype::text, ',')
    FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) g
   WHERE g.grantee IN (SELECT oid FROM runtime_roles)
  UNION ALL
  -- A7: every repository migration is applied, finished and not rolled back; none failed.
  SELECT 'A7_migration_ledger_complete',
         (SELECT count(*) FROM expected_migrations e WHERE NOT EXISTS (
            SELECT 1 FROM _prisma_migrations m WHERE m.migration_name = e.m AND m.finished_at IS NOT NULL AND m.rolled_back_at IS NULL))
         + (SELECT count(*) FROM _prisma_migrations m WHERE m.finished_at IS NULL AND m.rolled_back_at IS NULL),
         (SELECT count(*) FROM expected_migrations),
         (SELECT string_agg(e.m, ',' ORDER BY e.m) FROM expected_migrations e WHERE NOT EXISTS (
            SELECT 1 FROM _prisma_migrations m WHERE m.migration_name = e.m AND m.finished_at IS NOT NULL AND m.rolled_back_at IS NULL))
  UNION ALL
  -- A8: composite tenant FKs exist and are VALIDATED (NOT VALID = legacy cross-tenant rows exist).
  SELECT 'A8_tenant_fks_present_and_validated',
         count(*) FILTER (WHERE c.oid IS NULL OR NOT c.convalidated), count(*),
         string_agg(e.c || CASE WHEN c.oid IS NULL THEN ':missing' ELSE ':not_valid' END, ',' ORDER BY e.c)
           FILTER (WHERE c.oid IS NULL OR NOT c.convalidated)
    FROM expected_fks e LEFT JOIN pg_constraint c ON c.conname = e.c AND c.contype = 'f'
  UNION ALL
  -- A9: definer lookups are SECURITY DEFINER, search_path-pinned, and not executable by PUBLIC.
  SELECT 'A9_definer_lookups_hardened',
         count(*) FILTER (WHERE p.oid IS NULL OR NOT p.prosecdef
                          OR NOT coalesce(array_to_string(p.proconfig, ',') LIKE '%search_path=%', false)
                          OR has_function_privilege('public', p.oid, 'EXECUTE')),
         count(*),
         string_agg(e.f, ',' ORDER BY e.f) FILTER (WHERE p.oid IS NULL OR NOT p.prosecdef
                          OR NOT coalesce(array_to_string(p.proconfig, ',') LIKE '%search_path=%', false)
                          OR has_function_privilege('public', p.oid, 'EXECUTE'))
    FROM expected_fns e
    LEFT JOIN pg_proc p ON p.proname = e.f AND p.pronamespace = 'public'::regnamespace
)
SELECT id, CASE WHEN bad = 0 THEN 'PASS' ELSE 'FAIL' END AS result, bad AS failing, total AS checked,
       CASE WHEN bad = 0 THEN NULL ELSE left(detail, 2000) END AS failing_identifiers
  FROM results
 ORDER BY id;

ROLLBACK;
