import type { RenderPresetConfig, RenderPresetName } from "./types";

export const RENDER_PRESETS: Record<RenderPresetName, RenderPresetConfig> = {
  // ── Slow, warm, credibility-first ──────────────────────────────────────────
  trust_soft: {
    hookFontSize:       42,
    hookBgOpacity:      0.45,
    hookBorderRadius:   20,
    hookPaddingX:       22,
    hookPaddingY:       18,
    subtitleFontSize:   28,
    subtitleFontWeight: "600",
    subtitleBgOpacity:  0.50,
    subtitleY:          "82%",
    ctaFontSize:        32,
    ctaBgOpacity:       0.75,
    clipDurationDelta:  0.4,
    firstClipBonus:     0.3,
    lastClipBonus:      0.3,
    transitionPreset:   "fade",
    motionIntensity:    "low",
    subtitleRhythm:     "slow",
  },

  // ── Fast, punchy, high-contrast ────────────────────────────────────────────
  conversion_fast: {
    hookFontSize:       48,
    hookBgOpacity:      0.60,
    hookBorderRadius:   12,
    hookPaddingX:       18,
    hookPaddingY:       14,
    subtitleFontSize:   34,
    subtitleFontWeight: "700",
    subtitleBgOpacity:  0.65,
    subtitleY:          "87%",
    ctaFontSize:        38,
    ctaBgOpacity:       0.85,
    clipDurationDelta:  -0.2,
    firstClipBonus:     0.2,
    lastClipBonus:      0.2,
    transitionPreset:   "cut",
    motionIntensity:    "high",
    subtitleRhythm:     "punchy",
  },

  // ── Restrained, cinematic, whitespace-heavy ────────────────────────────────
  // subtitleBgOpacity: 0.0 → naked text on video (luxury aesthetic)
  luxury_clean: {
    hookFontSize:       40,
    hookBgOpacity:      0.25,
    hookBorderRadius:   0,
    hookPaddingX:       24,
    hookPaddingY:       20,
    subtitleFontSize:   26,
    subtitleFontWeight: "400",
    subtitleBgOpacity:  0.0,
    subtitleY:          "80%",
    ctaFontSize:        30,
    ctaBgOpacity:       0.70,
    clipDurationDelta:  0.6,
    firstClipBonus:     0.5,
    lastClipBonus:      0.5,
    transitionPreset:   "slow_fade",
    motionIntensity:    "minimal",
    subtitleRhythm:     "slow",
  },

  // ── Soft, rounded, B2C beauty / wellness ──────────────────────────────────
  beauty_aesthetic: {
    hookFontSize:       44,
    hookBgOpacity:      0.35,
    hookBorderRadius:   24,
    hookPaddingX:       20,
    hookPaddingY:       16,
    subtitleFontSize:   28,
    subtitleFontWeight: "600",
    subtitleBgOpacity:  0.45,
    subtitleY:          "83%",
    ctaFontSize:        32,
    ctaBgOpacity:       0.75,
    clipDurationDelta:  0.3,
    firstClipBonus:     0.3,
    lastClipBonus:      0.3,
    transitionPreset:   "dissolve",
    motionIntensity:    "low",
    subtitleRhythm:     "medium",
  },

  // ── Authentic, real-life, documentary feel ─────────────────────────────────
  documentary_real: {
    hookFontSize:       44,
    hookBgOpacity:      0.55,
    hookBorderRadius:   8,
    hookPaddingX:       20,
    hookPaddingY:       16,
    subtitleFontSize:   30,
    subtitleFontWeight: "600",
    subtitleBgOpacity:  0.60,
    subtitleY:          "85%",
    ctaFontSize:        34,
    ctaBgOpacity:       0.80,
    clipDurationDelta:  0.5,
    firstClipBonus:     0.4,
    lastClipBonus:      0.3,
    transitionPreset:   "cut",
    motionIntensity:    "low",
    subtitleRhythm:     "medium",
  },

  // ── TikTok-native, maximum energy, oversized text ──────────────────────────
  retail_tiktok: {
    hookFontSize:       52,
    hookBgOpacity:      0.65,
    hookBorderRadius:   24,
    hookPaddingX:       16,
    hookPaddingY:       12,
    subtitleFontSize:   36,
    subtitleFontWeight: "900",
    subtitleBgOpacity:  0.70,
    subtitleY:          "88%",
    ctaFontSize:        40,
    ctaBgOpacity:       0.90,
    clipDurationDelta:  -0.3,
    firstClipBonus:     0,
    lastClipBonus:      0.2,
    transitionPreset:   "cut",
    motionIntensity:    "high",
    subtitleRhythm:     "burst",
  },

  // ── Expert, clean, restrained authority ───────────────────────────────────
  authority_minimal: {
    hookFontSize:       44,
    hookBgOpacity:      0.50,
    hookBorderRadius:   4,
    hookPaddingX:       20,
    hookPaddingY:       16,
    subtitleFontSize:   30,
    subtitleFontWeight: "700",
    subtitleBgOpacity:  0.55,
    subtitleY:          "83%",
    ctaFontSize:        34,
    ctaBgOpacity:       0.80,
    clipDurationDelta:  0.2,
    firstClipBonus:     0.2,
    lastClipBonus:      0.4,
    transitionPreset:   "fade",
    motionIntensity:    "minimal",
    subtitleRhythm:     "slow",
  },

  // ── High energy, local SMB, punchy but not TikTok ─────────────────────────
  energetic_local: {
    hookFontSize:       50,
    hookBgOpacity:      0.60,
    hookBorderRadius:   16,
    hookPaddingX:       18,
    hookPaddingY:       14,
    subtitleFontSize:   34,
    subtitleFontWeight: "700",
    subtitleBgOpacity:  0.65,
    subtitleY:          "87%",
    ctaFontSize:        38,
    ctaBgOpacity:       0.85,
    clipDurationDelta:  -0.2,
    firstClipBonus:     0.1,
    lastClipBonus:      0.2,
    transitionPreset:   "cut",
    motionIntensity:    "high",
    subtitleRhythm:     "punchy",
  },

  // ── Warm, narrative, transformation arc ───────────────────────────────────
  emotional_story: {
    hookFontSize:       42,
    hookBgOpacity:      0.40,
    hookBorderRadius:   18,
    hookPaddingX:       22,
    hookPaddingY:       18,
    subtitleFontSize:   28,
    subtitleFontWeight: "600",
    subtitleBgOpacity:  0.50,
    subtitleY:          "82%",
    ctaFontSize:        32,
    ctaBgOpacity:       0.75,
    clipDurationDelta:  0.4,
    firstClipBonus:     0.4,
    lastClipBonus:      0.4,
    transitionPreset:   "dissolve",
    motionIntensity:    "low",
    subtitleRhythm:     "slow",
  },

  // ── Modern, editorial, SaaS / professional services ───────────────────────
  premium_modern: {
    hookFontSize:       42,
    hookBgOpacity:      0.35,
    hookBorderRadius:   12,
    hookPaddingX:       22,
    hookPaddingY:       18,
    subtitleFontSize:   28,
    subtitleFontWeight: "600",
    subtitleBgOpacity:  0.45,
    subtitleY:          "82%",
    ctaFontSize:        32,
    ctaBgOpacity:       0.70,
    clipDurationDelta:  0.3,
    firstClipBonus:     0.3,
    lastClipBonus:      0.4,
    transitionPreset:   "fade",
    motionIntensity:    "low",
    subtitleRhythm:     "medium",
  },
};
