export const OUTPUT_PROFILE_UNIFIED_CONFIDENCE_THRESHOLD = 0.6;

export const OUTPUT_PROFILE_CACHE_MAX_SIZE = 500;

export const OUTPUT_PROFILE_CACHE_TTL_MS_UNIFIED = 60 * 60 * 1000; // 60 minutes
export const OUTPUT_PROFILE_CACHE_TTL_MS_STORED = 3 * 60 * 1000; // 3 minutes

