import type { CreativeBlueprint } from "@/lib/features/content/creative-blueprint/types";
import type { HumanInsight } from "@/lib/features/content/human-insight/types";
import type { StoryPremise } from "@/lib/features/content/story-premise/types";

export type LLMPromptContext = {
  businessLabel: string;
  audienceLabel: string;
  mainOfferLabel: string;
  differentiatorLabel: string;
  goalLabel: string;
  contentGoalPrompt?: string;
  directionTitle?: string;
  directionDescription?: string;
  /** Internal fit note from direction card — briefing only, not spoken copy. */
  directionWhyItFits?: string;
  businessCategory?: string;
  /** Derived from `contentArchetypeId` — behavioral briefing for the model. */
  archetypeBehaviorBrief?: string;
  /** Generated by the Human Insight Layer — creative reasoning context, additive only. */
  humanInsight?: HumanInsight;
  /** Generated by the Story Premise Layer — the actual story to tell, additive only. */
  storyPremise?: StoryPremise;
};

export type LLMPromptPlan = {
  platform: string;
  videoType: string;
  structure: string[];
};

export type LLMPrompt = {
  system: string;
  user: string;
};

const STRUCTURE_LABELS: Record<string, string> = {
  hook:        "פתיחה",
  pain:        "כאב / בעיה",
  context:     "הקשר",
  explanation: "הסבר",
  solution:    "פתרון",
  proof:       "הוכחה",
  result:      "תוצאה",
  offer:       "הצעה",
  trust:       "אמון",
  value:       "ערך",
  cta:         "קריאה לפעולה",
};

function formatStructure(parts: string[]): string {
  return parts
    .map((p, i) => `  ${i + 1}. ${STRUCTURE_LABELS[p] ?? p}`)
    .join("\n");
}

function formatEmotionalArc(blueprint: CreativeBlueprint): string {
  if (!blueprint.emotional_arc.length) return "";
  const labels = blueprint.emotional_arc.map((s) => s.emotion);
  return `emotional_arc: ${labels.join(" → ")}`;
}

export function buildLLMPrompt(
  blueprint: CreativeBlueprint,
  context: LLMPromptContext,
  plan: LLMPromptPlan
): LLMPrompt {
  const pb = blueprint.platform_behavior;

  const system = `אתה כותב תוכן לרילים ברשתות — לא דף נחיתה, לא מודעה, לא מצגת מכירות.
המטרה: שהצופה יעצור בגלילה כי נאמר משהו חד — לא כי "ההצעה" מסודרת יפה.
אתה מקבל חומר רקע פנימי ו-CreativeBlueprint: תבין, תיישם בטון ובקצב — בלי לצטט את הרקע מילה במילה.
פלט: JSON בלבד. ללא markdown, ללא הסברים. רק אובייקט JSON תקין.`;

  const parts: string[] = [];

  // ─── Domain anchor (structured facts — not user free text) ─────────────────
  const anchorLines: string[] = [
    `# נושא וקהל`,
    `הסרטון הוא על: ${context.mainOfferLabel} של ${context.businessLabel}`,
    `קהל היעד: ${context.audienceLabel}`,
    `הסרטון פונה אל ${context.audienceLabel} — לא אל בעל העסק.`,
  ];
  parts.push(anchorLines.join("\n"));

  // ─── Blueprint ─────────────────────────────────────────────────────────────
  const arcLine = formatEmotionalArc(blueprint);
  parts.push(`# CreativeBlueprint
storytelling_model:  ${blueprint.storytelling_model}
attention_strategy:  ${blueprint.attention_strategy}
interruption_style:  ${blueprint.interruption_style}
pacing_curve:        ${blueprint.pacing_curve}
narration_tone:      ${blueprint.narration_tone}
narration_strategy:  ${blueprint.narration_strategy}
visual_strategy:     ${blueprint.visual_strategy}
visual_energy:       ${blueprint.visual_energy}
cta_psychology:      ${blueprint.cta_psychology}
subtitle_behavior:   ${blueprint.subtitle_behavior}${arcLine ? `\n${arcLine}` : ""}
platform_behavior:   hook=${pb.hookWindowSeconds}s | caption=${pb.captionStrategy} | hashtags=${pb.hashtagCount}
reasoning:           ${blueprint.blueprint_reasoning}`);

  // ─── Business context ──────────────────────────────────────────────────────
  parts.push(`# פרופיל עסקי
עסק:          ${context.businessLabel}
הצעת ערך:     ${context.mainOfferLabel}
קהל:          ${context.audienceLabel}
מטרה:         ${context.goalLabel}
יתרון ייחודי: ${context.differentiatorLabel}`);

  // ─── Human Insight Layer ──────────────────────────────────────────────────
  if (context.humanInsight) {
    const hi = context.humanInsight;
    parts.push(
      `# שכבת תובנה אנושית — לא לציטוט, לא לשעתוק ישיר — לחשיבה קריאייטיבית בלבד
הסרטון צריך לצמוח מהמקום הזה — לא להסביר אותו.
---
מצב אנושי: ${hi.humanSituation}
פרשנות רגשית: ${hi.emotionalInterpretation}
אמת נסתרת: ${hi.hiddenTruth}
מתח: ${hi.tension}
הזדמנות נרטיבית: ${hi.narrativeOpportunity}
מה הצופה אמור להרגיש: ${hi.viewerFeeling}
פיצוי רגשי: ${hi.payoff}
נתיב קריאייטיב: ${hi.creativeRoute}
תקשורת ישראלית: ${hi.israeliCommunicationDirection}`
    );
  }

  // ─── Story Premise Layer ──────────────────────────────────────────────────
  if (context.storyPremise) {
    const sp = context.storyPremise;
    parts.push(
      `# הסיפור שאתה מספר — לא לציטוט ישיר — כתוב shots שמגשימים אותו, לא שמסבירים אותו
---
רגע פתיחה: ${sp.openingMoment}
דמות: ${sp.protagonist}
ליבת הרגש: ${sp.emotionalCore}
קונפליקט: ${sp.conflict}
הסלמה: ${sp.escalation}
נקודת מפנה: ${sp.turningPoint}
payoff: ${sp.emotionalPayoff}
משמעות שיווקית: ${sp.marketingMeaning}

התקדמות הסצנות — השתמש בהן כ-creative anchor לכל shot במבנה:
${sp.sceneProgression.map((s, i) => `${i + 1}. ${s}`).join("\n")}`
    );
  }

  // ─── Internal briefing (never paste verbatim into hook/voice/caption/cta) ──
  const briefingChunks: string[] = [];
  if (context.contentGoalPrompt) {
    briefingChunks.push(
      `## מה שבעל העסק כתב (רקע להבנה — לא טקסט לקריאה במצלמה)\n${context.contentGoalPrompt}`
    );
  }
  if (context.directionTitle || context.directionDescription || context.directionWhyItFits) {
    const dirLines: string[] = ["## כיוון שנבחר (רקע אסטרטגי — לא לציטוט)"];
    if (context.directionTitle) dirLines.push(`כותרת כיוון: ${context.directionTitle}`);
    if (context.directionDescription) dirLines.push(`תיאור: ${context.directionDescription}`);
    if (context.directionWhyItFits) dirLines.push(`למה מתאים: ${context.directionWhyItFits}`);
    briefingChunks.push(dirLines.join("\n"));
  }
  if (context.archetypeBehaviorBrief) {
    briefingChunks.push(context.archetypeBehaviorBrief.trim());
  }
  if (briefingChunks.length) {
    parts.push(
      `# חומר רקע פנימי — לא להעתיק למלל הסרטון\n` +
        `הטקסטים בבלוק הזה נועדו רק כדי שתבין כוונה, הקשר וגבולות. אסור להחזיר משפטים מהם כפי שהם, אסור לצטט משפטי משתמש, אסור לנסח כאילו אתה מסכם brief.\n\n` +
        briefingChunks.join("\n\n")
    );
  }

  // ─── Task ──────────────────────────────────────────────────────────────────
  parts.push(`# משימה
פלטפורמה: ${plan.platform} | סוג סרטון: ${plan.videoType}
מבנה — ${plan.structure.length} שוטים בדיוק:
${formatStructure(plan.structure)}`);

  // ─── Rules ─────────────────────────────────────────────────────────────────
  parts.push(`# חוקי ביצוע

## עוגן תוכן — חובה
- הסרטון פונה לקהל: ${context.audienceLabel}. הוא מדבר אל הלקוחות, לא אל בעל העסק.
- כל hook, shot, voice ו-CTA חייבים להתייחס ישירות ל-${context.mainOfferLabel}.
- אסור לייצר תוכן כללי על: שיווק, צמיחה עסקית, הגדלת פניות, גרפי ביצועים, החלטות פיניסיות — אלא אם ${context.mainOfferLabel} הוא בפועל תחום פיננסי/שיווקי.
- visual: תאר מה רואים בפועל בתחום ${context.mainOfferLabel} — לא גרפים עסקיים כלליים, לא "ירידה בפניות" אלא אם זה קשור ישירות לתחום.
- אם העסק הוא B2C (קוסמטיקה, אופנה, מסעדה, עיצוב, טיפולים, שירות מקומי, בנייה, רפואה) — אסור שפת B2B. אסור אנימציות גרפי עסקים, דשבורדים, "להגדיל פניות".

## טון והתנהגות — אמירה, לא הסבר שיווקי
- ה-hook הוא לא מקום ל"להציג את המוצר". הוא מקום לטענה, למתח, לשבירת תפיסה, או לפנייה חדה — משהו שאדם אמיתי היה אומר לפני שהוא מסביר.
- עדיף משפט שמניח משהו ("רוב X לא צריכים Y", "אם בשביל Z צריך יום שלם — משהו שבור") על פני שאלת הצעה בסגנון דף נחיתה ("רוצים…?", "מחפשים…?", "רוצה X בלי Y?").
- מותר POV אישי (גוף ראשון) או פנייה ישירה קצרה לצופה — לפי מה שמתאים ל-blueprint; לא "אנחנו כחברה גאים להציג".
- קצב ריל: משפטים קצרים, נשימה ביניהם; לא פסקה ארוכה ב-hook. כל שוט voice = נקודה אחת ברורה, לא סיכום של כל הסיפור.
- מיישם interruption_style: ${blueprint.interruption_style} — הפרעה אמיתית, לא ניסוח מנומס.
- לא clickbait מוגזם ולא צעקות; עדיין חד ואנושי.

## שפה וסגנון (social-native, לא פרסומת)
- הכל בעברית — אסור אנגלית בטקסט
- כתיבה כמו יוצר/ת תוכן אמיתי ברשת — לא כמו מערכת, לא corporate, לא "קמפיין"
- hook: 1-2 משפטים בלבד — חד, לא גנרי, לא "פתיח מסביר"
- shots: בדיוק ${plan.structure.length} שוטים לפי המבנה לעיל
- visual: משפט אחד — מה שרואים / מצלמים ב-${context.mainOfferLabel}
- voice: 1-2 משפטים — עברית מדוברת; בלי ניסוחי מצגת, בלי "הפתרון המושלם", בלי "גלו איך", בלי "הורד עכשיו", בלי "האפליקציה שלנו מציעה"
- caption: ${pb.captionStrategy} style + ${pb.hashtagCount} האשטגים, עד 130 תווים
- cta: משפט אחד פעיל, מיישם cta_psychology: ${blueprint.cta_psychology} — לא לחיץ כמו באנר פרסומת
- אסור: "רוב האנשים", "אם גם אתם", "ככה זה נראה", "יש דרך", "זה ההבדל"
- אסור מטא-שיח על "מה שבחרתם", "הכיוון שבחרתם", "רציתם להבהיר", "זה מתחבר לנקודה" — אלה טקסטי מערכת
- אסור לצטט או לשעתק את חומר הרקע הפנימי (כולל משפטים שבעל העסק כתב במילים שלו)
- הטון חייב להתאים ל-narration_tone: ${blueprint.narration_tone}`);

  // ─── Output schema ─────────────────────────────────────────────────────────
  parts.push(`# פורמט הפלט (JSON בלבד)
{
  "hook": "...",
  "shots": [
    {"visual": "...", "voice": "..."}
  ],
  "caption": "...",
  "cta": "..."
}`);

  return {
    system,
    user: parts.join("\n\n"),
  };
}
