-- D2 / P7 Wave 2 — full rollback (policies + grants). Restores the pre-Wave-2
-- posture. Never drops roles; never touches pilot/Wave-1/W2-GATE substrate.
-- :ROLE = the environment's tenant runtime role.

-- Direct policies + RLS off (14)
DROP POLICY IF EXISTS p7w2_tenant ON "ContentRun";
ALTER TABLE "ContentRun" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "ContentRun" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "ContentEvent";
ALTER TABLE "ContentEvent" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "ContentEvent" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "LearningEvent";
ALTER TABLE "LearningEvent" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "LearningEvent" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "LearningSignal";
ALTER TABLE "LearningSignal" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "LearningSignal" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "Usage";
ALTER TABLE "Usage" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "Usage" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "FinancialDocument";
ALTER TABLE "FinancialDocument" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "FinancialDocument" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "Party";
ALTER TABLE "Party" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "Party" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "PartyResolutionClaim";
ALTER TABLE "PartyResolutionClaim" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "PartyResolutionClaim" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "RiaCanonicalReferent";
ALTER TABLE "RiaCanonicalReferent" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "RiaCanonicalReferent" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "RiaPolicyLineage";
ALTER TABLE "RiaPolicyLineage" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "RiaPolicyLineage" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "DerivedClaimProjection";
ALTER TABLE "DerivedClaimProjection" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "DerivedClaimProjection" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "DerivedClaimEvidenceLink";
ALTER TABLE "DerivedClaimEvidenceLink" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "DerivedClaimEvidenceLink" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "Recommendation";
ALTER TABLE "Recommendation" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "Recommendation" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "RecommendationOutcome";
ALTER TABLE "RecommendationOutcome" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationOutcome" DISABLE ROW LEVEL SECURITY;

-- Indirect policies + RLS off (10)
DROP POLICY IF EXISTS p7w2_tenant ON "BusinessBotProfile";
ALTER TABLE "BusinessBotProfile" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessBotProfile" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "BotGoalSelection";
ALTER TABLE "BotGoalSelection" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BotGoalSelection" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "BusinessBotSetupDraft";
ALTER TABLE "BusinessBotSetupDraft" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessBotSetupDraft" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "BusinessBotKnowledge";
ALTER TABLE "BusinessBotKnowledge" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessBotKnowledge" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "BusinessBotRecommendation";
ALTER TABLE "BusinessBotRecommendation" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessBotRecommendation" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "BusinessBotMemoryPolicy";
ALTER TABLE "BusinessBotMemoryPolicy" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessBotMemoryPolicy" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "BusinessBotLearningSuggestion";
ALTER TABLE "BusinessBotLearningSuggestion" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessBotLearningSuggestion" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "ContentVariant";
ALTER TABLE "ContentVariant" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "ContentVariant" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "ContentRender";
ALTER TABLE "ContentRender" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "ContentRender" DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p7w2_tenant ON "DerivedClaimCandidate";
ALTER TABLE "DerivedClaimCandidate" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "DerivedClaimCandidate" DISABLE ROW LEVEL SECURITY;

-- Wave-2 admin policy
DROP POLICY IF EXISTS p7adm_read ON "ContentRun";

-- Revoke Wave-2 runtime grants
REVOKE ALL PRIVILEGES ON "ContentRun" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "ContentRun_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "ContentVariant" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "ContentVariant_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "Usage" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBot" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBot_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotSettings" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBotSettings_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotProfile" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBotProfile_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BotGoalSelection" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BotGoalSelection_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotSetupDraft" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBotSetupDraft_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotKnowledge" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBotKnowledge_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotRecommendation" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBotRecommendation_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotMemoryPolicy" FROM :ROLE;
REVOKE ALL PRIVILEGES ON SEQUENCE "BusinessBotMemoryPolicy_id_seq" FROM :ROLE;
REVOKE ALL PRIVILEGES ON "BusinessBotLearningSuggestion" FROM :ROLE;

-- Revoke Wave-2 admin additions
REVOKE ALL PRIVILEGES ON "ContentRun" FROM app_admin;
REVOKE ALL PRIVILEGES ON "Document" FROM app_admin;
REVOKE ALL PRIVILEGES ON "EmailConnection" FROM app_admin;
REVOKE ALL PRIVILEGES ON "WhatsAppAttachmentImport" FROM app_admin;
