-- Phase 2 (secretary → ledger) — the secretary's WORKFLOW over an installment.
--
-- ADDITIVE ONLY. One new table; no existing table, column, row or policy is
-- touched. Reverting is `DROP TABLE "InstallmentWorkflow"` and loses nothing
-- financial, because nothing financial lives here:
--
--   followUpAt  snooze — hide from attention until then
--   handledAt   the owner said "טופל" — closes the reminder. handled ≠ paid:
--               money is only ever a Payment, and this is not an installment
--               status either (owner decision, Phase 2).
--
-- No column may change a due date, a coverage period, an allocated cost or a
-- cash figure; the Daily Business Cost engine never reads this table.

-- ── 1. Table (generated by `prisma migrate diff` from the datamodel) ─────────

CREATE TABLE "InstallmentWorkflow" (
    "installmentId" INTEGER NOT NULL,
    "businessId" INTEGER NOT NULL,
    "followUpAt" TIMESTAMP(3),
    "handledAt" TIMESTAMP(3),
    "handledByUserId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InstallmentWorkflow_pkey" PRIMARY KEY ("installmentId")
);

CREATE INDEX "InstallmentWorkflow_businessId_followUpAt_idx" ON "InstallmentWorkflow"("businessId", "followUpAt");

ALTER TABLE "InstallmentWorkflow" ADD CONSTRAINT "InstallmentWorkflow_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "InstallmentWorkflow" ADD CONSTRAINT "InstallmentWorkflow_installmentId_fkey" FOREIGN KEY ("installmentId") REFERENCES "Installment"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ── 2. Same business as its installment ─────────────────────────────────────
-- A foreign key cannot say "and the installment is this business's". This
-- trigger does, at the database, so a workflow row can never attach one
-- tenant's reminder to another tenant's installment. Under RLS the lookup only
-- sees the caller's own installments, so a foreign one is simply not found.

CREATE OR REPLACE FUNCTION "InstallmentWorkflow_same_business"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM "Installment" i
    WHERE i."id" = NEW."installmentId" AND i."businessId" = NEW."businessId"
  ) THEN
    RAISE EXCEPTION 'InstallmentWorkflow: installment % does not belong to business %',
      NEW."installmentId", NEW."businessId"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$fn$;

DROP TRIGGER IF EXISTS "InstallmentWorkflow_same_business" ON "InstallmentWorkflow";
CREATE TRIGGER "InstallmentWorkflow_same_business"
  BEFORE INSERT OR UPDATE OF "installmentId", "businessId" ON "InstallmentWorkflow"
  FOR EACH ROW EXECUTE FUNCTION "InstallmentWorkflow_same_business"();

-- ── 3. Tenant RLS — the same fail-closed predicate as every payables table ───

ALTER TABLE "InstallmentWorkflow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InstallmentWorkflow" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payables_p2_tenant ON "InstallmentWorkflow";
CREATE POLICY payables_p2_tenant ON "InstallmentWorkflow"
  USING ("businessId" = NULLIF(current_setting('app.current_business_id', true), '')::int)
  WITH CHECK ("businessId" = NULLIF(current_setting('app.current_business_id', true), '')::int);

-- ── 4. Grants, shipped with the definition ──────────────────────────────────
-- ALTER DEFAULT PRIVILEGES hands app_runtime a,r,w,d on every new table (see
-- 20260924180000). The workflow is reset by UPDATE, never deleted by the
-- application; rows go only when their installment or business does (CASCADE,
-- as the owner).
DO $do$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
    GRANT SELECT, INSERT, UPDATE ON "InstallmentWorkflow" TO app_runtime;
    REVOKE DELETE, TRUNCATE ON "InstallmentWorkflow" FROM app_runtime;
  END IF;
END
$do$;
