/**
 * M5.5 · The sensor catalogue — every event this contract is allowed to write, and nothing else.
 *
 * This is the machine-readable half of `docs/learning/SENSOR_COVERAGE.md`. A sensor that is not in
 * this list cannot be recorded (`recordSensor` refuses it), and every entry is checked by
 * `lib/sensors/sensors.test.ts`: past-tense occurrence names, no forbidden payload keys, a domain, a
 * version, and a sentence describing what happened.
 *
 * Existing `LearningEvent` types written through `logAuditEvent` (LEAD_*, BILLING_*, REVENUE_*, …) are
 * NOT redefined here: they keep their names so historical rows stay comparable, and now carry an
 * actor and a source. This catalogue holds the sensors that did not exist before M5.5.
 */
import type { SensorDefinition } from "./sensor.contract";

const S = <T extends SensorDefinition>(d: T): T => d;

export const SENSORS = {
  /* ─────────────────────────────── customers ─────────────────────────────── */
  CUSTOMER_CREATED: S({
    eventType: "CUSTOMER_CREATED",
    domain: "customers",
    entityType: "CUSTOMER",
    version: 1,
    payloadKeys: ["origin", "importRunId", "sourceRowNumber", "conversationId", "leadId"],
    describes: "A customer record came into existence, and through which path (UI, lead, WhatsApp, import, billing).",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Acquisition path exists only here; not consumed yet. Written by imports too, so its time is ingestion time." },
  }),
  CUSTOMER_UPDATED: S({
    eventType: "CUSTOMER_UPDATED",
    domain: "customers",
    entityType: "CUSTOMER",
    version: 1,
    payloadKeys: ["fields"],
    describes: "The owner changed a customer's details; which fields, never their values.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Field-name audit of an edit; the Customer row is the authority and an edit carries no learnable behaviour." },
  }),
  CUSTOMER_ARCHIVED: S({
    eventType: "CUSTOMER_ARCHIVED",
    domain: "customers",
    entityType: "CUSTOMER",
    version: 1,
    payloadKeys: [],
    describes: "The owner marked a customer inactive.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of an archive (Customer.isActive keeps no history); not consumed yet." },
  }),
  CUSTOMER_REACTIVATED: S({
    eventType: "CUSTOMER_REACTIVATED",
    domain: "customers",
    entityType: "CUSTOMER",
    version: 1,
    payloadKeys: [],
    describes: "The owner marked an inactive customer active again.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of a reactivation (Customer.isActive keeps no history); not consumed yet." },
  }),
  CUSTOMER_TAX_IDENTITY_CHANGED: S({
    eventType: "CUSTOMER_TAX_IDENTITY_CHANGED",
    domain: "customers",
    entityType: "CUSTOMER",
    version: 1,
    payloadKeys: ["fields"],
    describes: "The owner changed a customer's billing tax identity; which fields, never their values.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Identity audit trail; identity learning reads the Customer/claims ledger, not this event." },
  }),

  /* ─────────────────────────────── appointments ─────────────────────────────── */
  APPOINTMENT_STATUS_CHANGED: S({
    eventType: "APPOINTMENT_STATUS_CHANGED",
    domain: "appointments",
    entityType: "APPOINTMENT",
    version: 1,
    payloadKeys: ["from", "to"],
    describes: "An appointment moved between lifecycle states (confirmed, completed, cancelled, no-show).",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of an appointment's status history (Appointment keeps the current status only); not consumed yet." },
  }),
  APPOINTMENT_RESCHEDULED: S({
    eventType: "APPOINTMENT_RESCHEDULED",
    domain: "appointments",
    entityType: "APPOINTMENT",
    version: 1,
    payloadKeys: ["previousStartsAt", "startsAt", "durationChanged"],
    describes: "An appointment's time was changed; the previous and new start.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of a reschedule (business times are in the payload); not consumed yet." },
  }),

  /* ─────────────────────────────── suppliers / purchasing ─────────────────────────────── */
  SUPPLIER_CREATED: S({
    eventType: "SUPPLIER_CREATED",
    domain: "suppliers",
    entityType: "SUPPLIER",
    version: 1,
    payloadKeys: ["origin", "importRunId", "sourceRowNumber", "hasTaxId"],
    describes: "A supplier record came into existence, and through which path (UI or import).",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["Supplier"] },
  }),
  SUPPLIER_UPDATED: S({
    eventType: "SUPPLIER_UPDATED",
    domain: "suppliers",
    entityType: "SUPPLIER",
    version: 1,
    payloadKeys: ["fields", "taxIdChanged"],
    describes: "The owner changed a supplier's details; which fields, never their values.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["Supplier"] },
  }),
  SUPPLIER_DEACTIVATED: S({
    eventType: "SUPPLIER_DEACTIVATED",
    domain: "suppliers",
    entityType: "SUPPLIER",
    version: 1,
    payloadKeys: [],
    describes: "The owner marked a supplier inactive.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of a deactivation (Supplier.isActive keeps no history); not consumed yet." },
  }),
  SUPPLIER_REACTIVATED: S({
    eventType: "SUPPLIER_REACTIVATED",
    domain: "suppliers",
    entityType: "SUPPLIER",
    version: 1,
    payloadKeys: [],
    describes: "The owner marked an inactive supplier active again.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of a reactivation (Supplier.isActive keeps no history); not consumed yet." },
  }),
  SUPPLIER_PURCHASE_DRAFT_REJECTED: S({
    eventType: "SUPPLIER_PURCHASE_DRAFT_REJECTED",
    domain: "purchasing",
    entityType: "SUPPLIER_PURCHASE_DRAFT",
    version: 1,
    payloadKeys: ["lineCount"],
    describes: "The owner rejected a supplier purchase draft that intake had proposed.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["SupplierPurchaseDraft"] },
  }),
  PURCHASE_ORDER_STATUS_SETTLED: S({
    eventType: "PURCHASE_ORDER_STATUS_SETTLED",
    domain: "purchasing",
    entityType: "PURCHASE_ORDER",
    version: 1,
    payloadKeys: ["from", "to"],
    describes: "A purchase order reached a new settled status (e.g. CLOSED) after receiving or a remainder decision, and when.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["PurchaseOrder"] },
  }),
  PURCHASE_ORDER_REMAINDER_DECIDED: S({
    eventType: "PURCHASE_ORDER_REMAINDER_DECIDED",
    domain: "purchasing",
    entityType: "PURCHASE_ORDER_LINE",
    version: 1,
    payloadKeys: ["purchaseOrderId", "from", "to"],
    describes: "The owner decided what happens to an undelivered remainder (backorder or close short).",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["PurchaseOrderLine"] },
  }),

  /* ─────────────────────────────── inventory / POS ─────────────────────────────── */
  INVENTORY_ITEM_CREATED: S({
    eventType: "INVENTORY_ITEM_CREATED",
    domain: "inventory",
    entityType: "INVENTORY_ITEM",
    version: 1,
    payloadKeys: ["origin", "importRunId", "sourceRowNumber", "pendingMatchId", "supplierPurchaseDraftId"],
    describes: "An inventory item came into existence, and through which path.",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["InventoryItem"] },
  }),
  INVENTORY_ITEM_UPDATED: S({
    eventType: "INVENTORY_ITEM_UPDATED",
    domain: "inventory",
    entityType: "INVENTORY_ITEM",
    version: 1,
    payloadKeys: ["fields", "identityChanged", "thresholdsChanged", "deactivated", "reactivated"],
    describes: "The owner changed an item; which fields, and whether its SKU/barcode or stock thresholds changed.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Threshold edits; the one rule that would read them (INV-05 temporal) is blocked by the POS product defect." },
  }),
  INVENTORY_RECEIVING_POSTED: S({
    eventType: "INVENTORY_RECEIVING_POSTED",
    domain: "inventory",
    entityType: "RECEIVING_SESSION",
    version: 1,
    payloadKeys: ["purchaseOrderId", "movementIds", "lineCount"],
    describes: "A receiving session was posted; the stock movements it produced, as structured ids.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["ReceivingSession", "ReceivingLine", "InventoryMovement"] },
  }),
  POS_SALE_INGESTED: S({
    eventType: "POS_SALE_INGESTED",
    domain: "inventory",
    entityType: "INVENTORY_EXTERNAL_SALE",
    version: 1,
    payloadKeys: ["externalSaleId", "posSource", "movementIds", "lineCount", "outcome"],
    describes: "A POS sale arrived and was applied to stock, or held for matching; the movements it produced.",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["InventorySale", "InventorySaleLine", "InventorySourceSaleLine"] },
  }),
  POS_PENDING_MATCH_RESOLVED: S({
    eventType: "POS_PENDING_MATCH_RESOLVED",
    domain: "inventory",
    entityType: "INVENTORY_PENDING_MATCH",
    version: 1,
    payloadKeys: ["mode", "externalSaleId", "movementIds", "mappingReplaced"],
    describes: "The owner resolved a held POS sale (link, create, or reject); the movement it produced.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["InventoryPendingMatch"] },
  }),
  INVENTORY_DRAFT_DECIDED: S({
    eventType: "INVENTORY_DRAFT_DECIDED",
    domain: "inventory",
    entityType: "INVENTORY_DRAFT",
    version: 1,
    payloadKeys: ["decision", "itemId"],
    describes: "The owner approved, merged or rejected a photo-detected inventory draft.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["InventoryDraft"] },
  }),

  /* ─────────────────────────────── documents / data ─────────────────────────────── */
  DOCUMENT_INGESTED: S({
    eventType: "DOCUMENT_INGESTED",
    domain: "documents",
    entityType: "DOCUMENT",
    version: 1,
    payloadKeys: ["origin", "forcedDuplicate", "importRunId", "sourceRowNumber"],
    describes: "A document entered the system, through which path, and whether the owner forced a duplicate in.",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["Document"] },
  }),
  DOCUMENT_REPROCESS_REQUESTED: S({
    eventType: "DOCUMENT_REPROCESS_REQUESTED",
    domain: "documents",
    entityType: "DOCUMENT",
    version: 1,
    payloadKeys: ["outcome"],
    describes: "The owner asked for a document to be extracted again.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of an owner-requested reprocess; extraction reliability is not a business behaviour of the owner's business." },
  }),
  DATA_EXPORTED: S({
    eventType: "DATA_EXPORTED",
    domain: "data",
    entityType: "BUSINESS",
    version: 1,
    payloadKeys: ["kind", "format", "rowCount"],
    describes: "The owner exported business data out of Dubiz; which kind and how much.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of an export (accountant pack, CSV, uniform file); not consumed yet." },
  }),

  /* ─────────────────────────────── conversations ─────────────────────────────── */
  CONVERSATION_OPENED_MANUALLY: S({
    eventType: "CONVERSATION_OPENED_MANUALLY",
    domain: "conversations",
    entityType: "CONVERSATION",
    version: 1,
    payloadKeys: ["channel", "linkedCustomer", "linkedLead"],
    describes: "The owner opened a conversation by hand (not from an inbound message).",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["Conversation"] },
  }),
  CONVERSATION_CLOSED: S({
    eventType: "CONVERSATION_CLOSED",
    domain: "conversations",
    entityType: "CONVERSATION",
    version: 1,
    payloadKeys: ["previousStatus"],
    describes: "The owner closed a conversation.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["Conversation"] },
  }),
  CONVERSATION_HUMAN_TAKEOVER: S({
    eventType: "CONVERSATION_HUMAN_TAKEOVER",
    domain: "conversations",
    entityType: "CONVERSATION",
    version: 1,
    payloadKeys: ["draftsDismissed"],
    describes: "The owner took a conversation over from the bot; how many pending drafts were dismissed.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Only record of a takeover from the bot; not consumed yet." },
  }),

  /* ─────────────────────────────── settings ─────────────────────────────── */
  BUSINESS_PROFILE_CHANGED: S({
    eventType: "BUSINESS_PROFILE_CHANGED",
    domain: "settings",
    entityType: "BUSINESS",
    version: 1,
    payloadKeys: ["fields", "fromBusinessModel", "toBusinessModel"],
    // category is free text, so it appears only by name in `fields`; businessModel is a validated enum.
    describes: "The owner changed how the business describes itself (category, business model).",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Interpretation boundary for every baseline; no rule reads it yet." },
  }),
  BILLING_IDENTITY_CHANGED: S({
    eventType: "BILLING_IDENTITY_CHANGED",
    domain: "settings",
    entityType: "BUSINESS",
    version: 1,
    payloadKeys: ["fields", "fromBusinessKind", "toBusinessKind", "taxIdChanged", "vatNumberChanged"],
    describes: "The owner changed the business's billing identity; VAT status as from/to, identifiers as a flag only.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Billing identity audit; the BusinessProfile row is the authority and an edit carries no learnable behaviour." },
  }),
  BOT_SETTINGS_CHANGED: S({
    eventType: "BOT_SETTINGS_CHANGED",
    domain: "settings",
    entityType: "BUSINESS",
    version: 1,
    payloadKeys: ["fields", "fromEnabled", "toEnabled", "fromMode", "toMode"],
    describes: "The owner changed the assistant's settings; whether it was switched on or off, and its mode.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "AUDIT_ONLY", reason: "Bot configuration audit; the bot settings rows are the authority." },
  }),

  /* ─────────────────────────────── insights ─────────────────────────────── */
  INSIGHT_DECIDED: S({
    eventType: "INSIGHT_DECIDED",
    domain: "insights",
    entityType: "BUSINESS_INSIGHT",
    version: 1,
    payloadKeys: ["from", "to", "insightKind", "composerVersion", "noteGiven"],
    describes: "The owner explicitly decided on an insight; the previous and new decision. Silence writes nothing.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["BusinessInsight"] },
  }),

  /* ─────────────────────────────── payables (legacy obligations) ─────────────────────────────── */
  OBLIGATION_CHANGED: S({
    eventType: "OBLIGATION_CHANGED",
    domain: "payables",
    entityType: "BUSINESS_OBLIGATION",
    version: 1,
    payloadKeys: ["action", "fields", "amountChanged", "dueAtChanged"],
    describes: "A legacy obligation was created, edited, snoozed, completed, released, oriented or continued by its series.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["BusinessObligation"] },
  }),

  /* ─────────────────────────────── business intake (M3) ─────────────────────────────── */
  INTAKE_EVENT_SETTLED: S({
    eventType: "INTAKE_EVENT_SETTLED",
    domain: "intake",
    entityType: "INTAKE_EVENT",
    version: 1,
    payloadKeys: [
      "sourceKey",
      "family",
      "eventType",
      "outcome",
      "routeTarget",
      "identityOutcome",
      "attempts",
      "latencyMs",
    ],
    describes:
      "A business-intake receipt reached a terminal outcome (processed, ignored or dead-lettered): its source, family, route, attempts and latency.",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["IntakeEvent"] },
  }),
  INTAKE_IDENTITY_RESOLVED: S({
    eventType: "INTAKE_IDENTITY_RESOLVED",
    domain: "intake",
    entityType: "INTAKE_EVENT",
    version: 1,
    payloadKeys: ["state", "identifierKinds", "strongBases", "candidateCount", "policyVersion", "routingRule", "destination"],
    describes: "M4 resolved who an intake event is about (resolved, candidate, ambiguous, conflict, unresolved) and chose its route.",
    timeSemantics: "INGESTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["IntakeNormalizedEvent"] },
  }),
  IDENTITY_PROPOSAL_DECIDED: S({
    eventType: "IDENTITY_PROPOSAL_DECIDED",
    domain: "intake",
    entityType: "IDENTITY_PROPOSAL",
    version: 1,
    payloadKeys: ["action", "outcome"],
    describes: "The owner confirmed, rejected or undid an identity proposal, or it was found stale.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["IdentityProposal"] },
  }),

  /* ─────────────────────── leads — M5 lifecycle ─────────────────────── */
  // Written by lib/services/crm/lead-lifecycle.service.ts beside each LeadLifecycleEvent row.
  // Categories, counts and durations only: never a name, phone, email, note, reason text or amount.
  LEAD_LIFECYCLE_STARTED: S({
    eventType: "LEAD_LIFECYCLE_STARTED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["origin", "contactKnown"],
    describes: "A lead entered the CRM lifecycle, through which path (manual, conversation, auto-capture, import, intake), and whether its contact was already known.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
  LEAD_STAGE_CHANGED: S({
    eventType: "LEAD_STAGE_CHANGED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["fromStage", "toStage", "closing", "reopening", "hoursInPreviousStage"],
    describes: "The owner moved a lead from one lifecycle stage to another, and how long it had stayed in the previous stage.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
  LEAD_OUTCOME_RECORDED: S({
    eventType: "LEAD_OUTCOME_RECORDED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["outcome", "daysOpen", "hadNextAction"],
    describes: "A lead was closed as won, lost or dropped, after how many days, and whether a next action was still open.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
  LEAD_NEXT_ACTION_SCHEDULED: S({
    eventType: "LEAD_NEXT_ACTION_SCHEDULED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["actionKind", "rescheduled", "dueInHours", "fromSuggestion"],
    describes: "The owner set or postponed the next action on a lead: its kind, how far ahead, and whether it came from a Dubiz suggestion.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
  LEAD_NEXT_ACTION_COMPLETED: S({
    eventType: "LEAD_NEXT_ACTION_COMPLETED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["actionKind", "onTime", "lateHours"],
    describes: "The owner marked a lead's next action done, and whether it was done on time.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
  LEAD_FIRST_HANDLED: S({
    eventType: "LEAD_FIRST_HANDLED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["hoursToFirstHandling", "firstAction"],
    describes: "The owner took the first lifecycle action on a lead, how many hours after it arrived, and which action it was.",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
  LEAD_VALUE_RECORDED: S({
    eventType: "LEAD_VALUE_RECORDED",
    domain: "leads",
    entityType: "LEAD",
    version: 1,
    payloadKeys: ["amountKind", "cleared"],
    describes: "The owner recorded or cleared an estimated or agreed amount on a lead (the amount itself stays on the lead).",
    timeSemantics: "ACTION_TIME",
    learning: { role: "LEDGER_DUPLICATE", ledger: ["LeadLifecycleEvent"] },
  }),
} as const;

export type SensorKey = keyof typeof SENSORS;
