/**
 * Persistent login — the Prisma adapter. SERVER-ONLY.
 *
 * EVERY WRITE IN THIS FILE NAMES WHAT IT RETURNS. That is not style. A Prisma
 * write with no `select` appends `RETURNING` over every scalar column of the
 * model, `RETURNING` needs `SELECT` on what it returns, and on 2026-09-08 that
 * exact omission returned 500 on a CORRECT password in Production for two hours
 * — the write was permitted, the implicit read back was not. The auth plane here
 * happens to hold table-level `SELECT` on both tables, so an unnamed RETURNING
 * would work today; naming it anyway means a later narrowing of that grant
 * cannot reintroduce the same outage silently.
 *
 * EVERY TIMESTAMP IS A BOUND PARAMETER, never SQL `now()`. `TIMESTAMP(3)` in
 * this schema is WITHOUT time zone and `now()` is a timestamptz, so the database
 * would cast through a session TimeZone nobody sets. One captured instant per
 * operation also keeps the ordering between `lastUsedAt` and `graceUntil`
 * trustworthy, which the divergence rule depends on.
 *
 * PRIVILEGE CONTRACT this file is written against (migration
 * 20260908200000_auth_session_privilege_contract, applied in Production):
 *
 *   app_auth  SELECT  table-level on both
 *             INSERT  AuthSession: id,userId,secretHash,tokenVersionAtIssue,
 *                                  createdAt,lastUsedAt,idleExpiresAt,absoluteExpiresAt
 *                     AuthSessionSecret: id,sessionId,secretHash,rotatedAt,graceUntil
 *             UPDATE  AuthSession ONLY: secretHash,lastUsedAt,idleExpiresAt,
 *                                       revokedAt,revokedReason
 *             DELETE  table-level on both
 *   app_runtime  NOTHING on either table
 *
 * Nothing below writes `absoluteExpiresAt`, `tokenVersionAtIssue` or `userId`
 * after insert, and nothing updates `AuthSessionSecret` at all — not because the
 * code is careful, but because the database refuses. The 90-day ceiling, global
 * logout and session ownership are guarantees rather than promises.
 */
import type { Prisma, PrismaClient } from "@prisma/client";
import { authDb } from "@/lib/prisma-auth";
import { HISTORY_CAP } from "@/lib/auth/refresh-session";

/** Exactly the columns `decideRefresh` reads, plus the id it was found by. */
const SESSION_SELECT = {
  id: true,
  userId: true,
  secretHash: true,
  tokenVersionAtIssue: true,
  lastUsedAt: true,
  idleExpiresAt: true,
  absoluteExpiresAt: true,
  revokedAt: true,
} as const;

export type LoadedSession = {
  id: string;
  userId: number;
  secretHash: string;
  tokenVersionAtIssue: number;
  lastUsedAt: Date;
  idleExpiresAt: Date;
  absoluteExpiresAt: Date;
  revokedAt: Date | null;
};

type Db = PrismaClient | Prisma.TransactionClient;

/** Resolve a session by SELECTOR only. The secret is never part of the lookup. */
export async function loadSessionBySelector(
  sessionId: string,
  db: Db = authDb()
): Promise<LoadedSession | null> {
  return db.authSession.findUnique({ where: { id: sessionId }, select: SESSION_SELECT });
}

/**
 * The grace lookup: is the presented digest one THIS session issued?
 *
 * Scoped to the session on purpose. A digest is not a secret, but answering
 * "have you ever issued this?" across all sessions would leak one session's
 * history to the holder of another's selector.
 */
export async function loadRotatedSecret(
  sessionId: string,
  secretHash: string,
  db: Db = authDb()
): Promise<{ graceUntil: Date } | null> {
  return db.authSessionSecret.findUnique({
    where: { sessionId_secretHash: { sessionId, secretHash } },
    select: { graceUntil: true },
  });
}

/** The user facts a refresh needs, on the auth plane, within the E4 column grants. */
export async function loadUserForRefresh(
  userId: number,
  db: Db = authDb()
): Promise<{
  id: number;
  email: string;
  tokenVersion: number;
  businessId: number;
  business: { deletionRequestedAt: Date | null; deletedAt: Date | null } | null;
} | null> {
  return db.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      email: true,
      tokenVersion: true,
      businessId: true,
      business: { select: { deletionRequestedAt: true, deletedAt: true } },
    },
  });
}

export async function createSession(
  input: {
    userId: number;
    secretHash: string;
    tokenVersionAtIssue: number;
    createdAt: Date;
    lastUsedAt: Date;
    idleExpiresAt: Date;
    absoluteExpiresAt: Date;
  },
  db: Db = authDb()
): Promise<{ id: string; absoluteExpiresAt: Date }> {
  return db.authSession.create({
    data: input,
    // `id` is generated by the database default, so it must be read back — it is
    // the selector half of the credential and the caller cannot proceed without it.
    select: { id: true, absoluteExpiresAt: true },
  });
}

/**
 * One rotation, atomically.
 *
 * The outgoing secret is recorded BEFORE the session moves to the new one, in
 * the same transaction, so there is no instant in which a client holding the
 * outgoing secret would be classified as UNKNOWN — which is a 401 the user did
 * nothing to deserve.
 *
 * The history INSERT is tolerant of a unique-constraint collision: two
 * concurrent refreshes can legitimately try to record the SAME outgoing digest,
 * and the second one losing that race is not an error. `graceUntil` is written
 * once and can never be widened afterwards, because no UPDATE privilege exists
 * on this table at any level.
 */
export async function rotateSession(
  input: {
    sessionId: string;
    outgoingSecretHash: string;
    newSecretHash: string;
    now: Date;
    graceUntil: Date;
    idleExpiresAt: Date;
  },
  db: PrismaClient = authDb()
): Promise<{ rotated: boolean }> {
  return db.$transaction(async (tx) => {
    await tx.authSessionSecret
      .create({
        data: {
          sessionId: input.sessionId,
          secretHash: input.outgoingSecretHash,
          rotatedAt: input.now,
          graceUntil: input.graceUntil,
        },
        select: { id: true },
      })
      .catch((e: unknown) => {
        const code = (e as { code?: string } | null)?.code;
        // P2002 = the same outgoing digest is already recorded for this session,
        // by a concurrent rotation. The row we wanted exists; carry on.
        if (code !== "P2002") throw e;
      });

    // CONDITIONAL on the session still holding the digest we are replacing. Two
    // concurrent rotations from the same secret would otherwise both "succeed",
    // and the loser would hand its client a secret the session no longer has.
    const moved = await tx.authSession.updateMany({
      where: { id: input.sessionId, secretHash: input.outgoingSecretHash, revokedAt: null },
      data: {
        secretHash: input.newSecretHash,
        lastUsedAt: input.now,
        idleExpiresAt: input.idleExpiresAt,
      },
    });
    return { rotated: moved.count === 1 };
  });
}

/**
 * Revoke, conditionally and once. `revokedAt: null` in the predicate makes a
 * second revocation a no-op rather than a rewrite, so the first reason recorded
 * is the one that survives.
 */
export async function revokeSession(
  sessionId: string,
  reason: string,
  now: Date,
  db: Db = authDb()
): Promise<void> {
  await db.authSession.updateMany({
    where: { id: sessionId, revokedAt: null },
    data: { revokedAt: now, revokedReason: reason },
  });
}

/**
 * Opportunistic cleanup, user-scoped, best-effort.
 *
 * This product has no scheduler anywhere, so the only place this can run is
 * inside a user's own request. It therefore must never be able to fail one: a
 * caller that could not tidy up has still authenticated correctly. A permanently
 * dormant user's expired rows are never swept — bounded in size, unbounded in
 * time, and recorded as a deliberate limitation rather than an oversight.
 */
export async function sweepExpiredSessions(
  userId: number,
  now: Date,
  db: Db = authDb()
): Promise<number> {
  const { count } = await db.authSession.deleteMany({
    where: {
      userId,
      OR: [
        { revokedAt: { not: null } },
        { absoluteExpiresAt: { lt: now } },
        { idleExpiresAt: { lt: now } },
      ],
    },
  });
  return count;
}

/**
 * Cap eviction on the history table. A RESOURCE GUARD, never a security
 * invariant: evicting a row degrades a known secret to UNKNOWN, which is a 401
 * with no revocation — strictly more lenient, never less.
 */
export async function evictHistoryOverCap(
  sessionId: string,
  db: Db = authDb()
): Promise<number> {
  const total = await db.authSessionSecret.count({ where: { sessionId } });
  if (total <= HISTORY_CAP) return 0;
  const surplus = await db.authSessionSecret.findMany({
    where: { sessionId },
    orderBy: { rotatedAt: "asc" },
    take: total - HISTORY_CAP,
    select: { id: true },
  });
  if (surplus.length === 0) return 0;
  const { count } = await db.authSessionSecret.deleteMany({
    where: { id: { in: surplus.map((r) => r.id) } },
  });
  return count;
}

/** Delete one session outright. Used by logout, which has no reason to keep it. */
export async function deleteSession(sessionId: string, db: Db = authDb()): Promise<void> {
  await db.authSession.deleteMany({ where: { id: sessionId } });
}
